### ISSUE TITLE
No function clause matching in Wallaby.Query.ErrorMessage.method/2

### ISSUE THREAD

**Issue by viniciussbs** [keathley/wallaby#283]
When I call `assert_has(session, Query.text("my text"))` and Wallaby doesn't find an element with the text, I see this error:

```
** (FunctionClauseError) no function clause matching in Wallaby.Query.ErrorMessage.method/2
     stacktrace:
       (wallaby) lib/wallaby/query/error_message.ex:81: Wallaby.Query.ErrorMessage.method(:text, false)
       (wallaby) lib/wallaby/query/error_message.ex:65: Wallaby.Query.ErrorMessage.found_error_message/1
       (wallaby) lib/wallaby/query/error_message.ex:12: Wallaby.Query.ErrorMessage.message/2
```

When I change the call to:

```elixir
# the same xpath used by Query.text
assert_has(xpath(".//*[contains(normalize-space(text()), 'my text')]"))
```

I see the expected error message:

```
** (Wallaby.ExpectationNotMet) Expected to find 1, visible element that matched the xpath './/*[contains(normalize-space(text()), 'my text')]' but 0, visible elements were found.
```

Seems like `lib/wallaby/query/error_message.ex` is lacking these: 

```elixir
def method(:text, true), do: "texts"
def method(:text, false), do: "text"
```

**Comment by keathley** [comment]
Thanks @viniciussbs. I've submitted a PR which fixes this.
