### ISSUE TITLE
create-react-app documentation issue

### ISSUE THREAD

**Issue by FDiskas** [keathley/wallaby#361]
Reproduce:
1. `npm i -g create-react-app`
1. `create-react-app wallaby-error`
1. `cd wallaby-error`
1. `code .` (open IDE)
1. create new file **wallaby.js**
1. copy example from https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app
1. Run wallaby

**Errors:**
```
wallaby.js started
core v1.0.575
Error: spawn node ENOENT
    at _errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by PragTob** [comment]
Sorry there, this is the wrong wallaby - we're an elixir integration testing tool. [Their org is over here](https://github.com/wallabyjs).
