### ISSUE TITLE
Wallaby failing to start on CircleCi with new chromedriver version

### ISSUE THREAD

**Issue by tjshipe** [keathley/wallaby#419]
As of yesterday all of my CircleCi builds are failing when trying to start up Wallaby. I think this has something to do with a new version or versioning system for Chromedriver.

```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: 'lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2871]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3075]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 381]}, {Wallaby.Experimental.Chrome, :validate, 0, [file: 'lib/wallaby/experimental/chrome.ex', line: 36]}, {Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 27]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    test/test_helper.exs:1: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
Exited with code 1
```

**Comment by mhanberg** [comment]
What docker container are you using for your Circle CI builds? 

Mine seem to be fine. I'm using `circleci/elixir:1.8-node-browsers`

**Comment by tjshipe** [comment]
Hm, strange. I'm using that same container. It looks like there were a couple issues on circleci-images that could be related...

https://github.com/circleci/circleci-images/issues/355

**Comment by tjshipe** [comment]
I just upgrade my chromedriver locally `chromedriver 2.46 -> 73.0.3683.68` and I'm now seeing the error locally.

```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: 'lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2871]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3075]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 381]}, {Wallaby.Experimental.Chrome, :validate, 0, [file: 'lib/wallaby/experimental/chrome.ex', line: 36]}, {Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 27]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    test/test_helper.exs:1: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
```

**Comment by mhanberg** [comment]
Also, I am realizing there is a chance that I haven't upgraded yet. I use two different macs and can't remember which one I have upgraded recently. 

Tonight I will be able to confirm and see if I can reproduce locally.

**Comment by tjshipe** [comment]
Well, I goofed. I was unknowingly running an older version of Wallaby. If anyone else comes across this issue, wallby version 0.22 fixes the Chromedriver version issue.
