### ISSUE TITLE
Semi-random failure to start Wallaby on Heroku CI

### ISSUE THREAD

**Issue by jc00ke** [keathley/wallaby#427]
## Issue

Description of the issue. Please include browser you're using (phantomjs,
chrome, etc.) elixir and erlang version and any relevant stack traces.

- Erlang 21.1
- Elixir 1.8.1
- Wallaby 0.21 (haven't seen so far on 0.22)

I've been running Wallaby on Heroku CI with Chrome for months now with no issues. Last week, I started seeing errors when booting up Wallaby. I tried to see if there was a correlation between the version of Chrome installed by the buildpack (looks like v74 now) and the failures but I wasn't able to see exact versions. Anyway,  here's the stack trace:

```
03:57:25.898 [info] [swarm on nonode@nohost] [tracker:init] started

03:57:26.304 [info] Running X.Endpoint with cowboy 2.6.3 at 0.0.0.0:4001 (http)

03:57:26.322 [info] Access X.Endpoint at http://localhost:4001

03:57:26.763 [info] Application wallaby exited: exited in: Wallaby.start(:normal, [])

    ** (EXIT) an exception was raised:

        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Flow, GenEvent.Stream, List, IO.Stream, MapSet, Stream, Function, HashDict, Range, HashSet, File.Stream, Map, Date.Range

            (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1

            (elixir) /home/build/elixir/lib/elixir/lib/enum.ex:193: Enumerable.slice/1

            (elixir) lib/enum.ex:2871: Enum.backwards_compatible_slice/1

            (elixir) lib/enum.ex:3075: Enum.slice_any/3

            (elixir) lib/enum.ex:381: Enum.at/3

            (wallaby) lib/wallaby/experimental/chrome.ex:36: Wallaby.Experimental.Chrome.validate/0

            (wallaby) lib/wallaby.ex:27: Wallaby.start/2

            (kernel) application_master.erl:277: :application_master.start_it_old/4

03:57:26.765 [info] Application poolboy exited: :stopped

** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: nil}, [{Enumerable, :impl_for!, 1, [file: '/home/build/elixir/lib/elixir/lib/enum.ex', line: 1]}, {Enumerable, :slice, 1, [file: '/home/build/elixir/lib/elixir/lib/enum.ex', line: 193]}, {Enum, :backwards_compatible_slice, 1, [file: 'lib/enum.ex', line: 2871]}, {Enum, :slice_any, 3, [file: 'lib/enum.ex', line: 3075]}, {Enum, :at, 3, [file: 'lib/enum.ex', line: 381]}, {Wallaby.Experimental.Chrome, :validate, 0, [file: 'lib/wallaby/experimental/chrome.ex', line: 36]}, {Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 27]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}

    test/test_helper.exs:4: (file)

    (elixir) lib/code.ex:767: Code.require_file/2

    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2

    (elixir) lib/enum.ex:769: Enum.each/2

-----> Elixir buildpack tests failed with exit status 1
```

From the setup log:
```
Downloading chromedriver v74.0.3729.6
```

The same version was installed after the 0.21 -> 0.22 upgrade and Wallaby started normally.

Is anyone else seeing this? I upgraded from 0.21 to 0.22 and the errors, so far, have not resurfaced. Wanted to put it out there before I moved on, happy to close and have archived.

**Comment by jc00ke** [comment]
Shoulda looked through the `CHANGELOG` and PRs first... #403 :pray:
