### ISSUE TITLE
Setting selenium hub url not documented.

### ISSUE THREAD

**Issue by macabl** [keathley/wallaby#442]
I am trying to run my acceptance tests using docker-compose, but I am not sure how to set the selenium hub url.

I've tried configuring like this
```
# config/test.exs
config :wallaby,
  driver: Wallaby.Experimental.Selenium,
  selenium: [remote_url: "http://selenium:4444/wd/hub"],
  base_url: "http://web-test:#{unused_port_number}"
```

but when I run the tests I get this error:
```
** (RuntimeError) Wallaby had an internal issue with HTTPoison:
     %HTTPoison.Error{id: nil, reason: :econnrefused}
     stacktrace:
       (wallaby) lib/wallaby/httpclient.ex:37: Wallaby.HTTPClient.make_request/5
       (wallaby) lib/wallaby/experimental/selenium.ex:39: Wallaby.Experimental.Selenium.start_session/1
       (wallaby) lib/wallaby.ex:80: Wallaby.start_session/1
       test/acceptance/csv_upload_test.exs:84: EventUpload.CSVUploadTest.start_session/1
       test/acceptance/csv_upload_test.exs:1: EventUpload.CSVUploadTest.__ex_unit__/2

```

I am sure http://selenium points to my container running selenium because I can both ping and curl to it from my elixir container: web-test.

**Comment by michallepicki** [comment]
Good point. We definitely need better docs for Chromedriver and Selenium.

You should be able to pass `remote_url` to `start_session`, like this:
```
Wallaby.start_session(
  remote_url: "http://selenium:4444/wd/hub",
  capabilities: %{browserName: "firefox"}
)
```
