### ISSUE TITLE
Wallaby not working for ChromeDriver 76.0.3809.68

### ISSUE THREAD

**Issue by ulissesalmeida** [keathley/wallaby#449]
## Issue

Elixir version: 1.8.1
OTP: 21
Wallaby: 0.22.0
ChromeDriver: 76.0.3809.68

```
$ mix test
     ** (exit) exited in: GenServer.call(Wallaby.Driver.LogStore, {:get_and_update, #Function<0.5365077/1 in Wallaby.Driver.LogStore.append_logs/2>}, 5000)
         ** (EXIT) an exception was raised:
             ** (ArgumentError) argument error
                 :erlang.--(%{"error" => "invalid session id", "message" => "invalid session id", "stacktrace" => "0   chromedriver                        0x000000010e9c6129 chromedriver + 3649833\n1   chromedriver                        0x000000010e956133 chromedriver + 3191091\n2   chromedriver                        0x000000010e6f6b42 chromedriver + 703298\n3   chromedriver                        0x000000010e663fac chromedriver + 102316\n4   chromedriver                        0x000000010e68888c chromedriver + 252044\n5   chromedriver                        0x000000010e686bda chromedriver + 244698\n6   chromedriver                        0x000000010e686424 chromedriver + 242724\n7   chromedriver                        0x000000010e64f769 chromedriver + 18281\n8   chromedriver                        0x000000010e983c1f chromedriver + 3378207\n9   chromedriver                        0x000000010e98f940 chromedriver + 3426624\n10  chromedriver                        0x000000010e98f6d8 chromedriver + 3426008\n11  chromedriver                        0x000000010e964069 chromedriver + 3248233\n12  chromedriver                        0x000000010e9901b8 chromedriver + 3428792\n13  chromedriver                        0x000000010e977f07 chromedriver + 3329799\n14  chromedriver                        0x000000010e64da4e chromedriver + 10830\n15  libdyld.dylib                       0x00007fff58e283d5 start + 1\n16  ???                                 0x0000000000000003 0x0 + 3\n"}, [])
                 (wallaby) lib/wallaby/driver/log_store.ex:25: Wallaby.Driver.LogStore.unique_logs/2
                 (elixir) lib/map.ex:791: Map.get_and_update/3
                 (elixir) lib/agent/server.ex:16: Agent.Server.handle_call/3
                 (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

12:03:02.295 [error] gen_server 'Elixir.Wallaby.Driver.LogStore' terminated with reason: bad argument in call to erlang:'--'(#{<<"error">> => <<"invalid session id">>,<<"message">> => <<"invalid session id">>,<<"stackt...">> => ...}, []) in 'Elixir.Wallaby.Driver.LogStore':unique_logs/2 line 25
```

## Test Code & HTML

It's failing before reaching any HTML. It's not supporting the most recent ChromeDriver version.

**Comment by michallepicki** [comment]
Can you try adding `w3c: false` to start_session `capabilities:` option?

**Comment by michallepicki** [comment]
Hmm now I think this wouldn't work anyway as our module would try to add it to command-line args... This should be under `chromeOptions` [here](https://github.com/keathley/wallaby/blob/master/lib/wallaby/experimental/chrome.ex#L248), if it resolves the issue we could add that option to wallaby until we add support for the w3c protocol. But this could be another incompatibility, as well, we'll have to investigate

**Comment by michallepicki** [comment]
I just tried with `Google Chrome 76.0.3809.87` and `ChromeDriver 76.0.3809.68` (the same one as you) and it's working fine. Can you try a different Chrome version?

**Comment by ulissesalmeida** [comment]
I updated my Chrome and worked. Thank you. Sorry for any disturbance.

**Comment by michallepicki** [comment]
@ulissesalmeida No worries! I'm glad I could help
