### ISSUE TITLE
Wallaby won't stop using Chromium when using assert_has after a click

### ISSUE THREAD

**Issue by edouardmenayde** [keathley/wallaby#466]
## Issue

After a click is made in a form redirecting the user if `assert_has` is used then the test won't stop by itself until its killed by timeout of ExUnit.
Chromium version and Chromedriver version: 76.0.3809.132
Elixir version: 1.9.1
Erlang/OTP version : 21

## Test Code & HTML
test.eex
```elixir
defmodule SportyWeb.LoginTest do
  use SportyWeb.FeatureCase, async: true

  alias Sporty.Accounts

  @create_attrs %{email: "some.email@mail.com", password: "some passw0rd"}

  def fixture(:user) do
    {:ok, user} = Accounts.create_user(@create_attrs)
    user
  end

  setup [:create_user]

  test "users can login", %{session: session} do
    session
    |> visit(Routes.session_path(@endpoint, :new))
    |> find(css("#login-form"))
    |> fill_in(text_field("email"), with: @create_attrs.email)
    |> fill_in(text_field("password"), with: @create_attrs.password)
    |> click(button("login-btn"))
    |> assert_has(css(".phx-hero"))
    |> close_window() # does not anything unless I close the window myself in non headless mode then an error complains the window is already closed
  end

  defp create_user(_) do
    user = fixture(:user)
    {:ok, user: user}
  end
end
```
login_page.html.eex
```eex
<%= form_for @conn, @action, [id: "login-form"], fn f -> %>
  <div class="form-group">
      <label><%= gettext("Email") %></label>
      <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
      <label><%= gettext("Password") %></label>
      <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary", id: "login-btn" %>
  </div>
<% end %>
```

successful_redirect_page.html.eex
```eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Sporty" %></h1>
  <p>A new app.</p>
</section>
```

If a maintainer would like access to the repo to test by himself ask me I will add you to the repo since the project is pretty small and new.

**Comment by mhanberg** [comment]
@edouardmenayde do you mind providing a screenshot of before and after the line `|> assert_has(css(".phx-hero"))`?

```elixir
test "users can login", %{session: session} do
    session
    |> visit(Routes.session_path(@endpoint, :new))
    |> find(css("#login-form"))
    |> fill_in(text_field("email"), with: @create_attrs.email)
    |> fill_in(text_field("password"), with: @create_attrs.password)
    |> click(button("login-btn"))
    |> take_screenshot(log: true)
    |> assert_has(css(".phx-hero"))
    |> take_screenshot(log: true)
    |> close_window()
  end
```

What is the error message you are seeing?

Are you on the latest version of Wallaby?

Feel free to add me to your repo if you want.

**Comment by edouardmenayde** [comment]
@mhanberg I can only provide you with the screenshot of the first screenshot command since the second one is never made.
![1568183808446473635](https://user-images.githubusercontent.com/6023858/64673780-63109400-d46f-11e9-8d01-13667769c53d.png)

Here is the ExUnit error log :
```
 1) test users can login (SportyWeb.LoginTest)
     apps/sporty_web/test/sporty_web/features/login_test.exs:15
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)

     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).

     code: |> assert_has(css(".phx-hero"))
     stacktrace:
       (stdlib) gen.erl:169: :gen.do_call/4
       (stdlib) gen_server.erl:219: :gen_server.call/3
       (hackney) /home/edouard/code/sporty_umbrella/deps/hackney/src/hackney_response.erl:298: :hackney_response
.end_stream_body/2
       (hackney) /home/edouard/code/sporty_umbrella/deps/hackney/src/hackney_response.erl:155: :hackney_response
.stream_body1/2
       (hackney) /home/edouard/code/sporty_umbrella/deps/hackney/src/hackney_response.erl:309: :hackney_response
.read_body/3
       (hackney) /home/edouard/code/sporty_umbrella/deps/hackney/src/hackney.erl:515: anonymous fn/2 in :hackney
.body/2
       (httpoison) lib/httpoison/base.ex:802: HTTPoison.Base.request/6
       (wallaby) lib/wallaby/httpclient.ex:41: Wallaby.HTTPClient.make_request/5
       (wallaby) lib/wallaby/experimental/selenium/webdriver_client.ex:41: Wallaby.Experimental.Selenium.Webdriv
erClient.find_elements/2
       (wallaby) lib/wallaby/driver/log_checker.ex:6: Wallaby.Driver.LogChecker.check_logs!/2
       (wallaby) lib/wallaby/browser.ex:1140: anonymous fn/3 in Wallaby.Browser.execute_query/2
       (wallaby) lib/wallaby/browser.ex:146: Wallaby.Browser.retry/2
       test/sporty_web/features/login_test.exs:23: (test)
       (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

I'm using wallaby 0.23.0 (from the mix.lock).
I will add you to the repo, the code will be in branch `develop`

**Comment by mhanberg** [comment]
@edouardmenayde 

You will need to write your test in either of the following ways.

Fill in form inside callback to find. The [non-callback version](https://hexdocs.pm/wallaby/0.23.0/Wallaby.Browser.html#find/2) returns the element, which becomes the parent to the other functions. by the time you get to assert_has, you are referring to the form that is no longer on the page.
```elixir
  test "users can login", %{session: session} do
    session
    |> visit(Routes.session_path(@endpoint, :new))
    |> find(css("#login-form"), fn lf -> 
      lf
      |> fill_in(text_field("email"), with: @create_attrs.email)
      |> fill_in(text_field("password"), with: @create_attrs.password)
      |> click(button("login-btn"))
    end)
    |> assert_has(css(".phx-hero"))
  end
```

Or skip finding the form entirely. There aren't any other email or password fields on the page so we can find them from the root of the page.
```elixir
  test "users can login", %{session: session} do
    session
    |> visit(Routes.session_path(@endpoint, :new))
    # skip finding the form, we don't need it
    |> fill_in(text_field("email"), with: @create_attrs.email)
    |> fill_in(text_field("password"), with: "Wrong password")
    |> click(button("login-btn"))
    |> assert_has(css(".phx-hero"))
  end
```

**Comment by mhanberg** [comment]
For posterity, the reason why it was hanging was to do Chromedriver returning a StaleElementReference. (It was looking for the form element returned by `find`, but a new page had loaded since then).

We should probably emit a warning in this case.

**Comment by michallepicki** [comment]
@mhanberg But isn't the issue in question a separate one? I'd want the browsers to be always cleaned up even if a test times out.
