### ISSUE TITLE
Wallaby cannot find a button

### ISSUE THREAD

**Issue by lukerollans** [keathley/wallaby#56]
Hi there! First time using Wallaby on my first Phoenix app. I've written my first acceptance test but have run in to an issue I can't resolve on my own

It's very simple.. filling out a form to register a user.

#### The form
```
<%= form_for @changeset, organisation_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <p>Oh noes! Please check the errors below.</p>
  <% end %>

  <%= inputs_for f, :users, fn u -> %>
    <%= error_tag u, :first_name %>
    <%= text_input u, :first_name, placeholder: "First name" %>

    <%= error_tag u, :first_name %>
    <%= text_input u, :last_name, placeholder: "Last name" %>

    <%= error_tag u, :email %>
    <%= text_input u, :email, placeholder: "Email" %>
  <% end %>

  <%= error_tag f, :name %>
  <%= text_input f, :name, placeholder: "Organisation name" %>

  <div class="actions">
    <input type="submit" value="Submit" />
    <a href="#" class="forgot-password">Already signed up?</a>
  </div>
<% end %>
```

#### Acceptance test

```elixir
defmodule Esteem.UserSignsUpTest do
  use Esteem.AcceptanceCase, async: true

  test "user signs up a new organisation", %{session: session} do
    welcome_message =
      session
      |> visit("/")
      |> find("form")
      |> fill_in("First name", with: "Luke")
      |> fill_in("Last name", with: "Rollans")
      |> fill_in("Email", with: "some@email.com")
      |> fill_in("Organisation name", with: "Org name")
      |> click("Submit")
      |> find("p")
      |> text

    assert welcome_message =~ "Whelp"
  end
end
```

#### Error

```
  1) test user signs up a new organisation (Esteem.UserSignsUpTest)
     test/acceptance/user_signs_up_test.exs:4
     ** (Wallaby.ElementNotFound) Could not find element
     stacktrace:
       (wallaby) lib/wallaby/node.ex:342: Wallaby.Node.retry/2
       (wallaby) lib/wallaby/node.ex:192: Wallaby.Node.click/2
       test/acceptance/user_signs_up_test.exs:15
```

Seems that Wallaby cannot find the "Submit" button (line 15). I've tried using an ID, scoping a `find` to the `actions` wrapper, and other methods of detection to no vail.

Am I doing something glaringly wrong? I've read through the docs a few times and looked at test source code.. from what I can tell, it should work.

**Comment by keathley** [comment]
With the current version of the api you have to use the `click_button` helper. click is designed to work on Nodes directly. In the next release you actually won't be able to call click without the module name (`Node.click`) which should eliminate this confusion. Can you try again with the `click_button` helper?

**Comment by lukerollans** [comment]
@keathley when I try as you suggest, I'm getting `undefined function click_button/2`

Have I used it correctly?

```elixir
defmodule Esteem.UsertSignsUpTest do
  use Esteem.AcceptanceCase, async: true

  test "user signs up", %{session: session} do
    session
    |> visit("/")
    |> fill_in("First name", with: "Luke")
    |> fill_in("Last name", with: "Rollans")
    |> fill_in("Email", with: "hello@lukerollans.me")
    |> fill_in("Password", with: "123456")
    |> fill_in("Organisation name", with: "Marvellous Mutants")
    |> click_button("Submit")

    notice =
      session
      |> find(".alert.info")
      |> text

    assert notice == "Signed up successfully"
  end
end
```

**Comment by lukerollans** [comment]
Ah, I was using Wallaby `0.5.0`. `click_button` was introduced in `0.6.0`

**Comment by keathley** [comment]
Glad you got it sorted. :+1:
