### ISSUE TITLE
PhantomJS crashing

### ISSUE THREAD

**Issue by whw** [keathley/wallaby#91]
I have a relatively simple sign up form (the body html):

```
<div id="root">
  <div data-reactroot="" class="view-container registrations new">
    <main>
      <header>
        <div class="logo"></div>
      </header>
      <form>
        <div class="field"><input type="text" name="first_name" value="" placeholder="First name" required=""></div>
        <div class="field"><input type="text" name="last_name" value="" placeholder="Last name" required=""></div>
        <div class="field"><input type="email" name="email" value="" placeholder="Email" required=""></div>
        <div class="field"><input type="text" name="password" value="" placeholder="Password" required=""></div>
        <div class="field"><input type="password" name="password_confirmation" value="" placeholder="Confirm password" required=""></div>
        <button type="submit">Sign up</button><a href="/signin">Sign in</a>
      </form>
    </main>
  </div>
</div>
```

When I attempt to run this test:

```
  test "redirect to sign in", %{session: session} do
    user = %{
      first_name: "Jane",
      last_name: "Smith",
      email: "email-100@example.com",
      password: "password",
      encrypted_password: Comeonin.Bcrypt.hashpwsalt("password"),
    }

    session
    |> visit("/signup")
    |> fill_in("first_name", with: user.first_name)
  end
```

I reproducibly get this output:

```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.


  1) test redirect to sign in (MyApp.UserRegistrationTest)
     test/acceptance/user_registration_test.exs:4
     ** (RuntimeError) There was an error calling: http://localhost:50589/session/216548c0-6af0-11e6-873a-d74ddc1e1078/element/:wdc:1472149027298/value -> closed
     stacktrace:
       (wallaby) lib/wallaby/driver.ex:302: Wallaby.Driver.make_request/3
       (wallaby) lib/wallaby/driver.ex:274: Wallaby.Driver.check_logs!/2
       (wallaby) lib/wallaby/node.ex:58: Wallaby.Node.fill_in/2
       (wallaby) lib/wallaby/dsl/actions.ex:63: Wallaby.DSL.Actions.fill_in/3
       test/acceptance/user_registration_test.exs:18: (test)



Finished in 2.2 seconds
1 test, 1 failure

Randomized with seed 380223
```

I have another, similar test for which this doesn't happen at all - is there something I'm missing?

**Comment by whw** [comment]
PhantomJS 2.1.1
elixir 1.3.2
erlang 19.0
nodejs 6.3.1
wallaby 0.11.0

**Comment by whw** [comment]
This issue seems to have resolved itself 😕 

If it re-appears, I will try and capture the phantomjs webdriver log for more context.

**Comment by keathley** [comment]
Sorry about that @whw :(

This isn't something that I've seen before. I'm going to close this for now, but if it occurs again feel free to re-open the issue and I'll be happy to take a look at it.
